### ISSUE TITLE
Add ability to redirect to forward link after login

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#420]
In cases where we want to redirect someone to a link where they have to be signed in, we want to add the ability to redirect members to that link after they sign in.

**Comment by rgalanakis** [comment]
This is normally done with a query parameter that is looked for after auth, but in our case I think it's going to be gross to implement that way.

Instead let's do this:

- the 'redirect if unauthed' handler should set a value in session storage (so is cleared when the tab exits), named `sumaNextUrl`, with the value of the original URL (minus the host/etc). Then it should redirect as it currently does.
- After auth is complete (same for login and register), look for this `sumaNextUrl` value. If it's set, remove it, and instead of doing `navigate("/dashboard");`, navigate to the url. This will send you to the place you intended.
  - If you're not onboarded, it'll send you to `/onboarding` still, which will break the experience, but that's fine for now.
