### ISSUE TITLE
Error in map builder

### ISSUE THREAD

**Issue by rgalanakis** [lithictech/suma#461]
https://lithic-technology.sentry.io/issues/4310727558

Not sure when this is happening, maybe before the map is loaded/initialized? Run in chaos mode and see what happens.

**Comment by DeeTheDev** [comment]
@rgalanakis When the mapBuilder is initialized, it runs `getAndUpdateScooters` which will set a timer to refetch and update scooter data. The issue is that react mounts twice, the first refreshId is lost and we find a duplicated timers when the scooter async API call finishes setting the mapBuilder timer `_refreshId` property.
Reproduce steps:
1. Goto mobility page -> leave mobility page. Check Chrome debugger Network tab and you'll notice a hanging API call due to the above ^
2. Use console logs to show you the `_refreshId` in action from mapBuilder. Also add a comment after scooter is loaded in the Map component `console.log(map._refreshId)`. It will be null at first.

We need a solution where refreshId is captured once and removed when unmounted in that order, every time. This mean's we have to careful where the state is being managed and in what order it is being set.
